version: '3.8'

services:
  project-monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-monitoring
    restart: unless-stopped
    ports:
      - "3420:3420"  # Port in der Konfiguration anpassen
    volumes:
      - ./config:/app/config
      # Wir mounten nicht mehr den server-Ordner, da dies die installierten Module 端berschreiben w端rde
      - ./css:/app/css
      - ./js:/app/js
      - ./index.html:/app/index.html
    networks:
      - project-monitoring-network
    environment:
      - NODE_ENV=production
      - PORT=3420  # Port auch hier anpassen
    # Health check hinzuf端gen, um den Container-Status zu 端berwachen
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3420"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  project-monitoring-network:
    driver: bridge