apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-monitoring-config-pv
  labels:
    type: local
    app: project-monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/project-monitoring/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-monitoring-config-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-monitoring-sessions-pv
  labels:
    type: local
    app: project-monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/project-monitoring/sessions"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-monitoring-sessions-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi